### ISSUE TITLE
Too much padding above notice

### ISSUE THREAD

**Issue by ghost** [michael-bateman/projects.michaelbateman.ca#1]
There is too much spacing above your blue notice on your website.  Please fix!

**Comment by michael-bateman** [comment]
Hi @gafetest ,

Yes, I've found that bug multiple times.  I am working on fixing some bugs on my other websites.  Should be fixed soon

**Comment by michael-bateman** [comment]
Hi @gafetest ,

I have fixed the issue, please look below for information on the fix.

# Bug
## Issue
__Reported by:__ @gafetest 

There was too much spacing above the notices at the top of my website.

## Fix
Simple one, just change the css which is the `custom.css` file.
```css
body {
	padding-top: 50px;
}
```
to
```css
body {
	padding-top: 20px;
}
```
